web: gunicorn -w $UNICORN_N_WORKERS --timeout $UNICORN_TIMEOUT  app:FLASK_APP
worker: celery --app=celery_worker worker \
               --loglevel=INFO \
               --uid=nobody \
               --gid=nogroup
jobsmonitor: flower --app=celery_worker \
                    --broker=$REDIS_URL
postdeploy: alembic upgrade head
